### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by gnilix** [deepghs/waifuc#55]
FirstNSelectAction(60):   0%|                                                                   | 0/60 [00:03<?, ?it/s]
SaveExporter('/data/知更鸟3'): 32it [02:29,  4.66s/it]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "D:\data\3.py", line 29, in <module>
    source.export(
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 69, in export
    return exporter.export_from(iter(self))
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\export\base.py", line 32, in export_from
    for item in tqdm(items, desc=desc):
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 20, in __iter__
    yield from self._iter_from()
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 17, in _iter_from
    yield from self._iter()
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 98, in _iter
    yield from t
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\action\base.py", line 18, in iter_from
    for item in iter_:
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\action\base.py", line 18, in iter_from
    for item in iter_:
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\action\base.py", line 18, in iter_from
    for item in iter_:
  [Previous line repeated 3 more times]
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 20, in __iter__
    yield from self._iter_from()
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\compose.py", line 17, in _iter_from
    yield from self._iter()
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\compose.py", line 14, in _iter
    yield from iter(source)
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 20, in __iter__
    yield from self._iter_from()
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 17, in _iter_from
    yield from self._iter()
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 98, in _iter
    yield from t
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\action\base.py", line 70, in iter_from
    for item in tqdm(BaseAction.iter_from(self, iter_), desc=self._get_desc(), total=self.total):
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\action\base.py", line 18, in iter_from
    for item in iter_:
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 20, in __iter__
    yield from self._iter_from()
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\base.py", line 82, in _iter_from
    for item in tqdm(self._iter(), desc=desc):
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\web.py", line 136, in _iter
    yield from WebDataSource._iter(self)
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\web.py", line 48, in _iter
    for id_, url, meta in self._iter_data():
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\waifuc\source\anime_pictures.py", line 116, in _iter_data
    _, ext_name = os.path.splitext(urlsplit(url).filename)
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hbutils\system\network\url.py", line 81, in filename
    return self.path_segments[-1]
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hbutils\system\network\url.py", line 74, in path_segments
    return _split_path(self.path)
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hbutils\system\network\url.py", line 36, in _split_path
    return [urlparse.unquote(segment) for segment in path.split('/')]
TypeError: a bytes-like object is required, not 'str'

**Comment by lFitzl** [comment]
I also had this problem, so I deleted the installation and after a few days I reinstalled with `pip install -U git+https://github.com/deepghs/waifuc@main`

**Comment by little-KaoKao** [comment]
I met this error too. The code is very simple:

if __name__ == '__main__':
    s = E621Source(['stella_(helluva_boss)']) 
    s[:20].export(
        SaveExporter('data_original/stella_(helluva_boss)') #修改图片数量、替换保存路径
    )

It is very strange that it has already collected 11 pictures, then went wrong TypeError: a bytes-like object is required, not 'str'

**Comment by narugo1992** [comment]
seems some items have a `file_url` field of `None` value, thats why this error occurs

```python
            for data in page_items:
                try:
                    url = self._select_url(data)
                except NoURL:
                    continue

                # url is None here
                _, ext_name = os.path.splitext(urlsplit(url).filename)
```

**Comment by Yuersan** [comment]
> seems some items have a `file_url` field of `None` value, thats why this error occurs
> 
>             for data in page_items:
>                 try:
>                     url = self._select_url(data)
>                 except NoURL:
>                     continue
> 
>                 # url is None here
>                 _, ext_name = os.path.splitext(urlsplit(url).filename)

@narugo1992 Thx for your reply! I met this error as well, could you please advise me which section is to add these code in?

**Comment by little-KaoKao** [comment]
@Yuersan Tried again after 3 weeks and it seems to work now. It appears the issue was with the E621 website itself?

This section fix seems need to be implemented in the library's source code. I tried inheriting and overriding the method of the E621Source class, which successfully enabled crawling.

```
# Create a fixed version of E621Source class
class FixedE621Source(E621Source):
    def _select_url(self, data):
        url = super()._select_url(data)
        if url is not None:
            # Ensure URL is string type
            if isinstance(url, bytes):
                url = url.decode('utf-8')
        return url

# E621 - Use the fixed E621Source
if __name__ == '__main__':
    s = FixedE621Source(['nick_wilde'])  # Use the fixed E621Source class
    s[:10].export(
        SaveExporter('data_original/nick_wilde') # Modify image count and replace save path
    )
```
